[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
    knolleary/PubSubClient@^2.8
    arkhipenko/TaskScheduler@^3.7.0
    bblanchon/ArduinoJson@^6.21.3
    arduino-libraries/WiFi@^1.2.7

; Build flags for optimization
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    
; Upload settings
upload_speed = 921600
upload_port = COM12

; Monitor settings  
monitor_port = COM12
monitor_filters = esp32_exception_decoder
